import { ConnectionDocumentModel } from '../../domain/schemas/models/ConnectionDocumentModel';
import { CreateConnectionDocumentRequest } from '../dto/request/create-connection-document.request';
import { UpdateConnectionDocumentRequest } from '../dto/request/update-connection-document.request';
import { ConnectionDocumentResponse } from '../dto/response/connection-document.response';

export class CreateConnectionDocumentMapper {
  static fromRequestToModel(
    request: CreateConnectionDocumentRequest,
  ): ConnectionDocumentModel {
    return new ConnectionDocumentModel(
      '', // documentId will be generated by the database
      request.requestId,
      request.documentTypeId,
      request.fileUrl,
      request.originalName,
      request.mimeType,
      request.sizeInBytes,
      request.hashSha256,
      request.validationStatus,
      request.observation,
      null, // Set to empty string if validatorId is not provided
      null, // validationDate will be set to null by default
      false, // isDeleted will be false by default
      null, // deletedAt will be null by default
      new Date(), // createdAt will be set to current date
      new Date(), // updatedAt will be set to current date
    );
  }

  static fromModelToResponse(
    model: ConnectionDocumentModel,
  ): ConnectionDocumentResponse {
    return {
      documentId: model.documentId,
      requestId: model.requestId,
      documentTypeId: model.documentTypeId,
      fileUrl: model.fileUrl,
      originalName: model.originalName,
      mimeType: model.mimeType,
      sizeInBytes: model.sizeInBytes,
      hashSha256: model.hashSha256,
      validationStatus: model.validationStatus,
      observation: model.observation,
      validatorId: model.validatorId,
      validationDate: model.validationDate || null, // Handle null case for validationDate
      isDeleted: model.isDeleted,
      deletedAt: model.deletedAt || null, // Handle null case for deletedAt
      createdAt: model.createdAt,
      updatedAt: model.updatedAt,
    };
  }

  static fromRequestToModelForUpdate(
    request: UpdateConnectionDocumentRequest,
    existingModel: ConnectionDocumentModel,
  ): ConnectionDocumentModel {
    return new ConnectionDocumentModel(
      existingModel.documentId, // Keep the same documentId
      request.requestId,
      request.documentTypeId,
      request.fileUrl,
      request.originalName,
      request.mimeType,
      request.sizeInBytes,
      request.hashSha256,
      request.validationStatus,
      request.observation,
      request.validatorId,
      existingModel.validationDate, // Keep the same validationDate
      existingModel.isDeleted, // Keep the same isDeleted status
      existingModel.deletedAt, // Keep the same deletedAt value
      existingModel.createdAt, // Keep the same createdAt date
      new Date(), // Update updatedAt to current date
    );
  }
}
