import { InspectionInvoiceModel } from '../../domain/schemas/models/InspectionInvoiceModel';
import { CreateInspectionInvoiceRequest } from '../dto/request/create-inspection-invoice.request';
import { UpdateInspectionInvoiceRequest } from '../dto/request/update-inspection-invoice.request';
import { InspectionInvoiceResponse } from '../dto/response/inspection-invoice.response';

export class InspectionInvoiceMapper {
  static toModel(
    request: CreateInspectionInvoiceRequest,
  ): InspectionInvoiceModel {
    return new InspectionInvoiceModel(
      '', // invoiceId will be generated by the database
      request.requestId,
      request.invoiceNumber,
      request.conceptId,
      request.amount,
      'PENDIENTE', // Default status for new invoices
      request.expirationDate,
      null, // paymentDate will be null for new invoices
      request.paymentMethod || null,
      request.paymentReference || null,
      request.proofOfPayment || null,
      request.collectorId || null,
      new Date(), // createdAt will be set to current date
      new Date(), // updatedAt will be set to current date
    );
  }

  static toModelForUpdate(
    request: UpdateInspectionInvoiceRequest,
    existingModel: InspectionInvoiceModel,
  ): InspectionInvoiceModel {
    return new InspectionInvoiceModel(
      existingModel.invoiceId, // Keep the same invoiceId
      existingModel.requestId, // Keep the same requestId
      request.invoiceNumber || existingModel.invoiceNumber,
      request.conceptId || existingModel.conceptId,
      request.amount || existingModel.amount,
      existingModel.status, // Keep the same status
      request.expirationDate || existingModel.expirationDate,
      request.paymentDate || existingModel.paymentDate,
      request.paymentMethod || existingModel.paymentMethod,
      request.paymentReference || existingModel.paymentReference,
      request.proofOfPayment || existingModel.proofOfPayment,
      request.collectorId || existingModel.collectorId,
      existingModel.createdAt, // Keep the same createdAt
      new Date(), // updatedAt will be set to current date
    );
  }

  static toResponse(model: InspectionInvoiceModel): InspectionInvoiceResponse {
    return {
      invoiceId: model.invoiceId,
      requestId: model.requestId,
      invoiceNumber: model.invoiceNumber,
      conceptId: model.conceptId,
      amount: model.amount,
      status: model.status,
      expirationDate: model.expirationDate,
      paymentDate: model.paymentDate || null,
      paymentMethod: model.paymentMethod || null,
      paymentReference: model.paymentReference || null,
      proofOfPayment: model.proofOfPayment || null,
      collectorId: model.collectorId || null,
      createdAt: model.createdAt,
      updatedAt: model.updatedAt,
    };
  }

  static toResponseList(
    models: InspectionInvoiceModel[],
  ): InspectionInvoiceResponse[] {
    return models.map((model) => this.toResponse(model));
  }
}
